### ISSUE TITLE
Image tag is not respected

### ISSUE THREAD

**Issue by nicorikken** [cetic/helm-pgadmin#20]
The chart doesn't respect the `image.tag` property:

For now I've used this workaround:
```yaml
  image:
    # FIXME: temporary fix to fixate to a version tag
    repository: dpage/pgadmin4:4.13  # included tag here
    tag: 4.13  # is ignored
    pullPolicy: IfNotPresent
```
