### ISSUE TITLE
persistence.existingClaim is not considered

### ISSUE THREAD

**Issue by szamuboy** [cetic/helm-pgadmin#8]
Although there is a `persistence.existingClaim` value defined, it is not used in the actual Deployment [template](https://github.com/cetic/helm-pgadmin/blob/5fec913924a6c81f4deef78897e7c970c752710c/templates/deployment.yaml#L68).

```yaml
      volumes:
        - name: pgadmin-data
         {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "pgadmin.fullname" . }}
         {{- else }}
          emptyDir: {}
         {{- end }}
         {{- if .Values.pgadmin.tls }}
        - name: tls-private-key
          secret:
            secretName: {{ template "pgadmin.fullname" . }}
            items:
              - key: server.key
                path: server.key
```
